<?php

declare(strict_types=1);

return [
    'institutes' => [
        [
            'full_name_en' => 'HAN',
            'full_name_nl' => 'HAN',
            'short_name'   => 'HAN',
            'logo'         => 'HAN.png',
            'domain'       => 'han.nl',
            'banner'       => 'UT_banner.jpg',
        ],
        [
            'full_name_en' => 'Hanze University of Applied Sciences',
            'full_name_nl' => 'Hanzehogeschool Groningen',
            'short_name'   => 'Hanze',
            'logo'         => 'Hanze.png',
            'domain'       => 'hanze.nl',
            'banner'       => 'Hanze-banner.png',
        ],
        [
            'full_name_en' => 'Saxion University of Applied Sciences',
            'full_name_nl' => 'Saxion',
            'short_name'   => 'Saxion',
            'logo'         => 'Saxion.png',
            'domain'       => 'saxion.nl',
            'banner'       => 'Saxion_banner.jpg',
        ],
        [
            'full_name_en' => 'Inholland University of Applied Sciences',
            'full_name_nl' => 'Inholland',
            'short_name'   => 'Inholland',
            'logo'         => 'Inholland.png',
            'domain'       => 'inholland.nl',
            'banner'       => 'Inholland-banner.jpg',
        ],
        [
            'full_name_en' => 'University of Twente',
            'full_name_nl' => 'Universiteit Twente',
            'short_name'   => 'UT',
            'logo'         => 'UT.png',
            'domain'       => 'utwente.nl',
            'banner'       => 'UT_banner.jpg',
        ],
        [
            'full_name_en' => 'SURF',
            'full_name_nl' => 'SURF',
            'short_name'   => 'SURF',
            'logo'         => 'SURF.png',
            'domain'       => 'surf.nl',
            'banner'       => 'SURF_banner.jpg',
        ],
        [
            'full_name_en' => 'Erasmus University Rotterdam',
            'full_name_nl' => 'Erasmus Universiteit Rotterdam',
            'short_name'   => 'EUR',
            'logo'         => 'EUR-logo.jpg',
            'domain'       => 'eur.nl',
            'banner'       => 'EUR-banner.jpg',
        ],
        [
            'full_name_en' => 'Fontys University of Applied Sciences',
            'full_name_nl' => 'Fontys',
            'short_name'   => 'Fontys',
            'logo'         => 'Fontys-logo.jpg',
            'domain'       => 'fontys.nl',
            'banner'       => 'Fontys-banner.jpg',
        ],
        [
            'full_name_en' => 'Leiden University of Applied Sciences',
            'full_name_nl' => 'Hogeschool Leiden',
            'short_name'   => 'HS Leiden',
            'logo'         => 'hsleiden-logo.jpg',
            'domain'       => 'hsleiden.nl',
            'banner'       => 'hsleiden-202409-banner.jpg',
        ],
        [
            'full_name_en' => 'HZ University of Applied Sciences',
            'full_name_nl' => 'HZ',
            'short_name'   => 'HZ',
            'logo'         => 'hz-logo.jpg',
            'domain'       => 'hz.nl',
            'banner'       => 'hz_banner.jpg',
        ],
        [
            'full_name_en' => 'ArtEZ University of the Arts',
            'full_name_nl' => 'ArtEZ University of the Arts',
            'short_name'   => 'ArtEZ',
            'logo'         => 'artez-logo.png',
            'domain'       => 'artez.nl',
            'banner'       => 'artez-banner.jpg',
        ],
        [
            'full_name_en' => 'Breda University of Applied Sciences',
            'full_name_nl' => 'Breda University of Applied Sciences',
            'short_name'   => 'BUas',
            'logo'         => 'BUas.jpg',
            'domain'       => 'buas.nl',
            'banner'       => 'BUas-banner.jpg',
        ],
        [
            'full_name_en' => 'Maastricht University',
            'full_name_nl' => 'Universiteit Maastricht',
            'short_name'   => 'UM',
            'logo'         => 'maastrichtuniversity.jpg',
            'domain'       => 'maastrichtuniversity.nl',
            'banner'       => 'um-banner.jpg',
        ],
        [
            'full_name_en' => 'ROC Midden Nederland',
            'full_name_nl' => 'ROC Midden Nederland',
            'short_name'   => 'ROC MN',
            'logo'         => 'rocmn_logo.jpg',
            'domain'       => 'rocmn.nl',
            'banner'       => 'rocmn_banner.jpg',
        ],
        [
            'full_name_en' => 'Tilburg University',
            'full_name_nl' => 'Universiteit Tilburg',
            'short_name'   => 'TiU',
            'logo'         => 'tilburg-university-logo.jpg',
            'domain'       => 'uvt.nl',
            'banner'       => 'tilburg-university-banner.jpg',
        ],
        [
            'full_name_en' => 'Deltion College',
            'full_name_nl' => 'Deltion College',
            'short_name'   => 'Deltion',
            'logo'         => 'deltion-logo.jpg',
            'domain'       => 'deltion.nl',
            'banner'       => 'deltion-banner.png',
        ],
        [
            'full_name_en' => 'HU University of Applied Sciences Utrecht',
            'full_name_nl' => 'Hogeschool Utrecht',
            'short_name'   => 'HU',
            'logo'         => 'hu-logo.jpg',
            'domain'       => 'hu.nl',
            'banner'       => 'hu-banner.jpg',
        ],
        [
            'full_name_en' => 'Wageningen University & Research',
            'full_name_nl' => 'Wageningen University & Research',
            'short_name'   => 'WUR',
            'logo'         => 'wur_logo.jpg',
            'domain'       => 'wur.nl',
            'banner'       => 'wur_sfeerbeeld.jpg',
        ],
        [
            'full_name_en' => 'NHL Stenden University of Applied Sciences',
            'full_name_nl' => 'NHL Stenden Hogeschool',
            'short_name'   => 'NHL Stenden',
            'logo'         => 'nhlstendenhogeschool_logo.jpg',
            'domain'       => 'nhlstenden.com',
            'banner'       => 'nhlstendenhogeschool_banner.jpg',
        ],
        [
            'full_name_en' => 'Rijn IJssel',
            'full_name_nl' => 'Rijn IJssel',
            'short_name'   => 'Rijn IJssel',
            'logo'         => 'rijnijssel-logo.jpg',
            'domain'       => 'rijnijssel.nl',
            'banner'       => 'rijnijssel-banner-temp.jpg',
        ],
    ],

    'test-institutes' => [
        [
            'full_name_en' => 'EduID',
            'full_name_nl' => 'EduID',
            'short_name'   => 'EduID',
            'logo'         => 'EduID.png',
            'domain'       => 'eduid.nl',
            'banner'       => 'UT_banner.jpg',
        ],
    ],
];
