name: Quick Checks

on:
  push:
    branches-ignore:
      - develop
      - accept
      - master

jobs:
  code-analysis:
    name: Code Analysis
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}

    steps:
      - uses: actions/checkout@v2

      - name: Set Up PHP and Tools
        uses: shivammathur/setup-php@master
        with:
          php-version: "8.0"
          tools: composer:v2
          coverage: none

      - name: Setup Analysis Environment
        run: yes | cp .env.testing.example .env

      - name: Install Composer Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Static Code Analysis
        run: ./vendor/bin/phpstan analyse --memory-limit=2G

  code-style:
    name: Code Style
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set Up PHP and Tools
        uses: shivammathur/setup-php@master
        with:
          php-version: "8.0"
          tools: composer:v2, phpcs, php-cs-fixer, phpmd, phpcpd
          coverage: none

      - name: Install required NVM version
        run: . ~/.nvm/nvm.sh && nvm install 14

      - name: Syntax Errors
        run: find app database tests config routes -name "*.php" -print0 | xargs -0 -n1 -P8 php -l

      - name: PHP_CodeSniffer
        run: phpcs

      - name: PHP-CS-Fixer
        run: php-cs-fixer fix app database config routes tests --dry-run --diff --allow-risky=yes --config=.php-cs-fixer.php

      - name: PHPMD
        run: phpmd app text phpmd.xml

      - name: PHPCPD
        run: phpcpd app --exclude app/Http/Controllers/InformationManager/Prohibited/ToolController.php

      - name: Lint Assets
        run: ./lintHook.sh $PWD

  security-check:
    name: Security Check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set Up PHP and Tools
        uses: shivammathur/setup-php@master
        with:
          php-version: "8.0"
          tools: composer:v2
          coverage: none

      - name: Check Composer Packages
        uses: symfonycorp/security-checker-action@v2
